### ISSUE TITLE
Making web based application using streamlit and use for users (improvement )

### ISSUE THREAD

**Issue by chandankumarm55** [anish1204/Voice-to-text-Pyhton#1]
We can enhance the existing Voice-to-Text Conversion app by adding features like language selection, audio playback, and the ability to download transcriptions. After these improvements, we can deploy the app on Streamlit Cloud to make it easily accessible online. Please assign this issue to me so I can implement the enhancements and handle the deployment process.

Assign this issue to me , i would like to contribute this repo .

**Comment by anish1204** [comment]
Also try merging this code with other frontend lib like reactjs

**Comment by chandankumarm55** [comment]
you'r saying to make same voice to text  application in react also ?

**Comment by anish1204** [comment]
No just make it in python 
Then we could make a React app that provides input and this python application acts as a service to the react App
What say?

**Comment by chandankumarm55** [comment]
Today, I will be creating a PR and sharing the deployed link. Please merge it, then create an issue and assign it to me. I will work on it as expected

**Comment by chandankumarm55** [comment]
I Have created PR can u just merge it please

**Comment by chandankumarm55** [comment]
Can please response if you need any other feature let me know , please merge it main branch , and also i see many of your repo has not finished and also not deployed react apps so if you need any kind contribution please let me know
